package com.loki.todo.workflow;

public enum WorkflowEventType {
    TODO_CREATED,
    TODO_UPDATED,
    TODO_COMPLETED,
    TODO_STARTED,
    TODO_MOVED_TO_REVIEW,
    TODO_BLOCKED,
    TODO_UNBLOCKED,
    TODO_ASSIGNED,
    TODO_PRIORITY_CHANGED,
    TODO_DUE_DATE_CHANGED,
    TODO_MOVED,
    TODO_MOVED_COLUMN,
    TODO_TIME_LOGGED,
    TODO_ARCHIVED,
    TODO_RESTORED,
    BOARD_COLUMN_ADDED,
    BOARD_COLUMN_RENAMED,
    TODO_DELETED, BOARD_COLUMN_DELETED
}